//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDMProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDMProject.Resources.PropertyNames", typeof(PropertyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualne hasło.
        /// </summary>
        public static string ChangePasswordViewModel_OldPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź nowe hasło.
        /// </summary>
        public static string Common_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Common_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź hasło.
        /// </summary>
        public static string Common_ConfirmPassword {
            get {
                return ResourceManager.GetString("Common_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        public static string Common_NewPassword {
            get {
                return ResourceManager.GetString("Common_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Common_Password {
            get {
                return ResourceManager.GetString("Common_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe informacje.
        /// </summary>
        public static string EditProfileViewModel_AdditionalComment {
            get {
                return ResourceManager.GetString("EditProfileViewModel_AdditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string EditProfileViewModel_City {
            get {
                return ResourceManager.GetString("EditProfileViewModel_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr mieszkania.
        /// </summary>
        public static string EditProfileViewModel_FlatNumber {
            get {
                return ResourceManager.GetString("EditProfileViewModel_FlatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter.
        /// </summary>
        public static string EditProfileViewModel_HasAdapterAvailable {
            get {
                return ResourceManager.GetString("EditProfileViewModel_HasAdapterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maska.
        /// </summary>
        public static string EditProfileViewModel_HasMaskAvailable {
            get {
                return ResourceManager.GetString("EditProfileViewModel_HasMaskAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkt zbioru masek.
        /// </summary>
        public static string EditProfileViewModel_HasMaskCollectionPoint {
            get {
                return ResourceManager.GetString("EditProfileViewModel_HasMaskCollectionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr domu.
        /// </summary>
        public static string EditProfileViewModel_HouseNumber {
            get {
                return ResourceManager.GetString("EditProfileViewModel_HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię i nazwisko.
        /// </summary>
        public static string EditProfileViewModel_Name {
            get {
                return ResourceManager.GetString("EditProfileViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string EditProfileViewModel_PhoneNumber {
            get {
                return ResourceManager.GetString("EditProfileViewModel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        public static string EditProfileViewModel_PostalCode {
            get {
                return ResourceManager.GetString("EditProfileViewModel_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string EditProfileViewModel_StreetName {
            get {
                return ResourceManager.GetString("EditProfileViewModel_StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie?.
        /// </summary>
        public static string LoginViewModel_RememberMe {
            get {
                return ResourceManager.GetString("LoginViewModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeczytałem i akceptuję regulamin.
        /// </summary>
        public static string RegisterViewModel_AcceptTerms {
            get {
                return ResourceManager.GetString("RegisterViewModel_AcceptTerms", resourceCulture);
            }
        }
    }
}
