//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDMProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDMProject.Resources.PropertyNames", typeof(PropertyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string Address_City {
            get {
                return ResourceManager.GetString("Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr mieszkania.
        /// </summary>
        public static string Address_FlatNumber {
            get {
                return ResourceManager.GetString("Address_FlatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr domu.
        /// </summary>
        public static string Address_HouseNumber {
            get {
                return ResourceManager.GetString("Address_HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        public static string Address_PostalCode {
            get {
                return ResourceManager.GetString("Address_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string Address_StreetName {
            get {
                return ResourceManager.GetString("Address_StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź nowe hasło.
        /// </summary>
        public static string ChangePasswordViewModel_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        public static string ChangePasswordViewModel_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualne hasło.
        /// </summary>
        public static string ChangePasswordViewModel_OldPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordynator.
        /// </summary>
        public static string CollectionPoint_Coordinator {
            get {
                return ResourceManager.GetString("CollectionPoint_Coordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inny koordynator....
        /// </summary>
        public static string CollectionPoint_OtherCoordinator {
            get {
                return ResourceManager.GetString("CollectionPoint_OtherCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane koordynatora (imię, nazwisko, dane kontaktowe).
        /// </summary>
        public static string CollectionPoint_OtherCoordinatorDetails {
            get {
                return ResourceManager.GetString("CollectionPoint_OtherCoordinatorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź hasło.
        /// </summary>
        public static string Common_ConfirmPassword {
            get {
                return ResourceManager.GetString("Common_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordynowanych.
        /// </summary>
        public static string Coordinator_CoordinatedPeopleCount {
            get {
                return ResourceManager.GetString("Coordinator_CoordinatedPeopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordynowany region.
        /// </summary>
        public static string Coordinator_CoordinatedRegion {
            get {
                return ResourceManager.GetString("Coordinator_CoordinatedRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie?.
        /// </summary>
        public static string LoginViewModel_RememberMe {
            get {
                return ResourceManager.GetString("LoginViewModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeczytałem i akceptuję regulamin.
        /// </summary>
        public static string RegisterViewModel_AcceptTerms {
            get {
                return ResourceManager.GetString("RegisterViewModel_AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - wybierz -.
        /// </summary>
        public static string SelectList_Placeholder {
            get {
                return ResourceManager.GetString("SelectList_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe informacje.
        /// </summary>
        public static string User_AdditionalComment {
            get {
                return ResourceManager.GetString("User_AdditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string User_CompanyName {
            get {
                return ResourceManager.GetString("User_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba kontaktowa.
        /// </summary>
        public static string User_ContactName {
            get {
                return ResourceManager.GetString("User_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię i nazwisko.
        /// </summary>
        public static string User_IndividualName {
            get {
                return ResourceManager.GetString("User_IndividualName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string User_PhoneNumber {
            get {
                return ResourceManager.GetString("User_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię i nazwisko.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ użytkownika.
        /// </summary>
        public static string User_UserType {
            get {
                return ResourceManager.GetString("User_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string User_UserType_Company {
            get {
                return ResourceManager.GetString("User_UserType_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba fizyczna.
        /// </summary>
        public static string User_UserType_IndividualPerson {
            get {
                return ResourceManager.GetString("User_UserType_IndividualPerson", resourceCulture);
            }
        }
    }
}
