//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDMProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDMProject.Resources.ViewResources", typeof(ViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Account_ChangePassword__Save {
            get {
                return ResourceManager.GetString("Account_ChangePassword__Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string Account_ChangePassword__Title {
            get {
                return ResourceManager.GetString("Account_ChangePassword__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywuj konto, aby móc korzystać z serwisu..
        /// </summary>
        public static string Account_ConfirmationEmailSent__ActivateAccountToUseService {
            get {
                return ResourceManager.GetString("Account_ConfirmationEmailSent__ActivateAccountToUseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na adres {0} został wysłany mail z linkiem aktywacyjnym..
        /// </summary>
        public static string Account_ConfirmationEmailSent__LinkHasBeenSent {
            get {
                return ResourceManager.GetString("Account_ConfirmationEmailSent__LinkHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź adres e-mail.
        /// </summary>
        public static string Account_ConfirmationEmailSent__Title {
            get {
                return ResourceManager.GetString("Account_ConfirmationEmailSent__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaloguj się!.
        /// </summary>
        public static string Account_ConfirmEmail__Login {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail__Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę,.
        /// </summary>
        public static string Account_ConfirmEmail__Please {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail__Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzięki za rejestrację!.
        /// </summary>
        public static string Account_ConfirmEmail__Title {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj email, aby zresetować hasło.
        /// </summary>
        public static string Account_ForgotPassword__Placeholder {
            get {
                return ResourceManager.GetString("Account_ForgotPassword__Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeśli zapomniałeś hasła do swojego konta, to wystarczy, że podasz swój email, a my wyślemy Ci kod do zmiany hasła..
        /// </summary>
        public static string Account_ForgotPassword__ProvideEmailAndWeSendResetPassword {
            get {
                return ResourceManager.GetString("Account_ForgotPassword__ProvideEmailAndWeSendResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string Account_ForgotPassword__Send {
            get {
                return ResourceManager.GetString("Account_ForgotPassword__Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zresetuj hasło.
        /// </summary>
        public static string Account_ForgotPassword__Title {
            get {
                return ResourceManager.GetString("Account_ForgotPassword__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeżeli dany e-mail istnieje w naszym serwisie, to na podany adres e-mail wysłany został link do zresetowania hasła..
        /// </summary>
        public static string Account_ForgotPasswordConfirmation__MessageSent {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmation__MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie zmiany hasła.
        /// </summary>
        public static string Account_ForgotPasswordConfirmation__Title {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmation__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie pamiętam hasła.
        /// </summary>
        public static string Account_Login__ForgotPassword {
            get {
                return ResourceManager.GetString("Account_Login__ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string Account_Login__Header {
            get {
                return ResourceManager.GetString("Account_Login__Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string Account_Login__Login {
            get {
                return ResourceManager.GetString("Account_Login__Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string Account_Login__Title {
            get {
                return ResourceManager.GetString("Account_Login__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie mam jeszcze konta.
        /// </summary>
        public static string Account_Login_DontHaveAnAccount {
            get {
                return ResourceManager.GetString("Account_Login_DontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz.
        /// </summary>
        public static string Account_Register__Open {
            get {
                return ResourceManager.GetString("Account_Register__Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się.
        /// </summary>
        public static string Account_Register__Register {
            get {
                return ResourceManager.GetString("Account_Register__Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        public static string Account_Register__Title {
            get {
                return ResourceManager.GetString("Account_Register__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Account_ResetPassword__Reset {
            get {
                return ResourceManager.GetString("Account_ResetPassword__Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset hasła.
        /// </summary>
        public static string Account_ResetPassword__Title {
            get {
                return ResourceManager.GetString("Account_ResetPassword__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kliknij i zaloguj się.
        /// </summary>
        public static string Account_ResetPasswordConfirmation__ClickAndLogin {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation__ClickAndLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło zresetowane,.
        /// </summary>
        public static string Account_ResetPasswordConfirmation__PasswordHasBeenReset {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation__PasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset hasła potwierdzony.
        /// </summary>
        public static string Account_ResetPasswordConfirmation__Title {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywni.
        /// </summary>
        public static string AdminLayout__CollectionPoints_Active {
            get {
                return ResourceManager.GetString("AdminLayout__CollectionPoints_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratorzy.
        /// </summary>
        public static string AdminLayout__CollectionPoints_Admins {
            get {
                return ResourceManager.GetString("AdminLayout__CollectionPoints_Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkty zbiórki.
        /// </summary>
        public static string AdminLayout__CollectionPoints_All {
            get {
                return ResourceManager.GetString("AdminLayout__CollectionPoints_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordynatorzy.
        /// </summary>
        public static string AdminLayout__CollectionPoints_Coordinators {
            get {
                return ResourceManager.GetString("AdminLayout__CollectionPoints_Coordinators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieukończone profile.
        /// </summary>
        public static string AdminLayout__CollectionPoints_Unfinished {
            get {
                return ResourceManager.GetString("AdminLayout__CollectionPoints_Unfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niezweryfikowani.
        /// </summary>
        public static string AdminLayout__CollectionPoints_Unverified {
            get {
                return ResourceManager.GetString("AdminLayout__CollectionPoints_Unverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wróć do strony głównej.
        /// </summary>
        public static string Error__BackToHomePage {
            get {
                return ResourceManager.GetString("Error__BackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string Error__Error {
            get {
                return ResourceManager.GetString("Error__Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod błędu.
        /// </summary>
        public static string Error__ErrorCode {
            get {
                return ResourceManager.GetString("Error__ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas przetwarzania twojego żądania..
        /// </summary>
        public static string Error__ErrorOccuredWhilePerformingRequest {
            get {
                return ResourceManager.GetString("Error__ErrorOccuredWhilePerformingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd.
        /// </summary>
        public static string Error__Title {
            get {
                return ResourceManager.GetString("Error__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jestem.
        /// </summary>
        public static string Home_Index__Im {
            get {
                return ResourceManager.GetString("Home_Index__Im", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jestem Medykiem.
        /// </summary>
        public static string Home_Index__ImAMedic {
            get {
                return ResourceManager.GetString("Home_Index__ImAMedic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jestem Dostawcą.
        /// </summary>
        public static string Home_Index__ImASupplier {
            get {
                return ResourceManager.GetString("Home_Index__ImASupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulamin.
        /// </summary>
        public static string Home_Rodo__Title {
            get {
                return ResourceManager.GetString("Home_Rodo__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maska dla medyka.
        /// </summary>
        public static string Layout__MainPageLink {
            get {
                return ResourceManager.GetString("Layout__MainPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maska dla medyka.
        /// </summary>
        public static string Layout__Title {
            get {
                return ResourceManager.GetString("Layout__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż/ukryj nawigację.
        /// </summary>
        public static string Layout__ToggleNavigation {
            get {
                return ResourceManager.GetString("Layout__ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto zablokowane.
        /// </summary>
        public static string Lockout__AccountLocked {
            get {
                return ResourceManager.GetString("Lockout__AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To konto zostało zablokowane, spróbuj ponownie później..
        /// </summary>
        public static string Lockout__AccountLockedTryAgainLater {
            get {
                return ResourceManager.GetString("Lockout__AccountLockedTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto zablokowane.
        /// </summary>
        public static string Lockout__Title {
            get {
                return ResourceManager.GetString("Lockout__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel administracyjny.
        /// </summary>
        public static string LoginPartial__AdminPanel {
            get {
                return ResourceManager.GetString("LoginPartial__AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string LoginPartial__ChangePassword {
            get {
                return ResourceManager.GetString("LoginPartial__ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj profil.
        /// </summary>
        public static string LoginPartial__EditProfile {
            get {
                return ResourceManager.GetString("LoginPartial__EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzupełnij swój profil!.
        /// </summary>
        public static string LoginPartial__FinishProfile {
            get {
                return ResourceManager.GetString("LoginPartial__FinishProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string LoginPartial__Login {
            get {
                return ResourceManager.GetString("LoginPartial__Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string LoginPartial__Logout {
            get {
                return ResourceManager.GetString("LoginPartial__Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        public static string LoginPartial__Register {
            get {
                return ResourceManager.GetString("LoginPartial__Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż profil.
        /// </summary>
        public static string LoginPartial__ShowProfile {
            get {
                return ResourceManager.GetString("LoginPartial__ShowProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostarczane produkty.
        /// </summary>
        public static string Manage_EditProfile__AvailableProducts {
            get {
                return ResourceManager.GetString("Manage_EditProfile__AvailableProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Manage_EditProfile__Cancel {
            get {
                return ResourceManager.GetString("Manage_EditProfile__Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj profil.
        /// </summary>
        public static string Manage_EditProfile__EditProfile {
            get {
                return ResourceManager.GetString("Manage_EditProfile__EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieszkanie.
        /// </summary>
        public static string Manage_EditProfile__Flat {
            get {
                return ResourceManager.GetString("Manage_EditProfile__Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznacz adres na mapie.
        /// </summary>
        public static string Manage_EditProfile__MarkAddressOnMap {
            get {
                return ResourceManager.GetString("Manage_EditProfile__MarkAddressOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Więcej informacji w.
        /// </summary>
        public static string Manage_EditProfile__MoreInfo {
            get {
                return ResourceManager.GetString("Manage_EditProfile__MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Manage_EditProfile__Save {
            get {
                return ResourceManager.GetString("Manage_EditProfile__Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznaczenie opcji „maska”, „adapter” lub &quot;punkt zbiórki masek&quot; powoduje automatyczne opublikowanie w Serwisie danych podanych w profilu..
        /// </summary>
        public static string Manage_EditProfile__SelectingWillPublishProfile {
            get {
                return ResourceManager.GetString("Manage_EditProfile__SelectingWillPublishProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulaminie.
        /// </summary>
        public static string Manage_EditProfile__TermsAndConditions {
            get {
                return ResourceManager.GetString("Manage_EditProfile__TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj profil.
        /// </summary>
        public static string Manage_EditProfile__Title {
            get {
                return ResourceManager.GetString("Manage_EditProfile__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje zmiany zostały zapisane. Możesz teraz przejść do mapy..
        /// </summary>
        public static string Manage_ShowProfile__ChangesSavedGoToMap {
            get {
                return ResourceManager.GetString("Manage_ShowProfile__ChangesSavedGoToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejdź do mapy.
        /// </summary>
        public static string Manage_ShowProfile__GoToMap {
            get {
                return ResourceManager.GetString("Manage_ShowProfile__GoToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój profil został zaktualizowany i oczekuje na potwierdzenie przez koordynatora. Otrzymasz potwierdzenie email, gdy tylko koordynator potwierdzi Twoją tożsamość..
        /// </summary>
        public static string Manage_ShowProfile__ProfileUpdatedAndAwaitingApproval {
            get {
                return ResourceManager.GetString("Manage_ShowProfile__ProfileUpdatedAndAwaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukces.
        /// </summary>
        public static string Manage_ShowProfile__Success {
            get {
                return ResourceManager.GetString("Manage_ShowProfile__Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój profil.
        /// </summary>
        public static string Manage_ShowProfile__Title {
            get {
                return ResourceManager.GetString("Manage_ShowProfile__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój profil.
        /// </summary>
        public static string Manage_ShowProfile__YourProfile {
            get {
                return ResourceManager.GetString("Manage_ShowProfile__YourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista dostępnych.
        /// </summary>
        public static string Map_Index__AvailableList {
            get {
                return ResourceManager.GetString("Map_Index__AvailableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popraw kod pocztowy.
        /// </summary>
        public static string Map_Index__FixPostalCode {
            get {
                return ResourceManager.GetString("Map_Index__FixPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        public static string Map_Index__PostalCode {
            get {
                return ResourceManager.GetString("Map_Index__PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        public static string Map_Index__Search {
            get {
                return ResourceManager.GetString("Map_Index__Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        public static string Map_Index__Title {
            get {
                return ResourceManager.GetString("Map_Index__Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - BRAK -.
        /// </summary>
        public static string UsersList__NoData {
            get {
                return ResourceManager.GetString("UsersList__NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukces!.
        /// </summary>
        public static string UsersList__Success {
            get {
                return ResourceManager.GetString("UsersList__Success", resourceCulture);
            }
        }
    }
}
